# Generated by Django 5.2.3 on 2025-07-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0003_topic_alter_post_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='topics',
        ),
    ]
