# Generated by Django 5.2.3 on 2025-07-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0004_rename_topic_topic_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
