# Generated by Django 5.2.3 on 2025-07-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0006_topic_alter_post_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
