# Generated by Django 5.2.3 on 2025-07-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0007_remove_post_topic_delete_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='about',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
