# Generated by Django 5.2.3 on 2025-07-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0009_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
