# Generated by Django 5.2.3 on 2025-07-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0010_alter_post_about_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='about',
            field=models.CharField(max_length=500),
        ),
    ]
