# Generated by Django 5.2.3 on 2025-07-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0011_alter_post_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('marks', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
