# Generated by Django 5.2.3 on 2025-07-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0012_students_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
